mod animation;
mod audio;
mod callback_query;
mod chat;
mod contact;
mod document;
mod file;
mod games;
mod inline_mode;
mod input_media;
mod location;
mod message;
mod passport;
mod payments;
mod photo_size;
mod primitive;
mod reply_markup;
mod response;
mod stickers;
mod update;
mod user;
mod venue;
mod video;
mod video_note;
mod voice;

pub use self::animation::*;
pub use self::audio::*;
pub use self::callback_query::*;
pub use self::chat::*;
pub use self::contact::*;
pub use self::document::*;
pub use self::file::*;
pub use self::games::*;
pub use self::inline_mode::*;
pub use self::input_media::*;
pub use self::location::*;
pub use self::message::*;
pub use self::passport::*;
pub use self::payments::*;
pub use self::photo_size::*;
pub use self::primitive::*;
pub use self::reply_markup::*;
pub use self::response::*;
pub use self::stickers::*;
pub use self::update::*;
pub use self::user::*;
pub use self::venue::*;
pub use self::video::*;
pub use self::video_note::*;
pub use self::voice::*;
